import pathlib,json,numpy as np
P=pathlib.Path(__file__).resolve().parent.parent/'outputs/drive_analysis_20260930'
j=json.loads((P/'metrics.json').read_text());inv=json.loads((P/'inventory.json').read_text()); integ=json.loads((P/'download_integrity.json').read_text())
rows=[r for r in j['routes'] if r['qualified']['seconds']>0];g=j['aggregate']
faults=[]
for r in rows:
 a=np.load(P/(r['route']+'.npz'));c=a['cs'];mask=(c[:,2]>=10)&(c[:,6]>0);ix=np.where(mask)[0];groups=np.split(ix,np.where(np.diff(ix)>1)[0]+1)
 for group in groups:
  if len(group):faults.append({'route':r['route'],'from_first_carState_seconds':float(c[group[0],0]-c[0,0]),'duration_approx_seconds':float(c[group[-1],0]-c[group[0],0]+.01),'speed_mph':float(np.median(c[group,2])*2.236936),'driver_pressed_fraction':float(np.mean(c[group,4]))})
(P/'temporary_fault_intervals.json').write_text(json.dumps(faults,indent=2))
report=['# Stock-identity EPS drive baseline','', 'Analysis date: September 30, 2026. Retrieved read-only over SSH from the comma; no software, firmware, or tuning changes were made.','',f'Copied **{len(integ)} full rlogs across {len(inv)} routes**, {sum(r["bytes"] for r in integ):,} compressed bytes. All {len(integ)} SHA-256 hashes match the source device snapshot. qlogs and the device Cap’n Proto schemas were also copied.','', '## Identity and configuration','', 'All route inventories report `39990-THR-A020`; none reports `39990-THR,A020`. This is a **stock-identity baseline**, not an independent firmware-byte verification. Every route records openpilot commit `b3366b5b56512805be8f0bf832b4981bfd958072`, branch `nrdr-clean`. The earlier Connect route `000000b0--bce0d61278` is not in this local set.','', '| Recorded parameter | Value |','|---|---|','| kpV | 0.28 |','| kiV | 0.08 |','| kf | 0.00006 |','| torqueBP / torqueV | [0,4096] / [0,4096] |','| Configured actuator delay | 0.10 s |','', 'Logged P/error ratios in the two longer assisted routes agree with kp=0.28. Configuration values are not proof of physical torque calibration.','', '## Qualified baseline','', f'Three routes contain lateral assistance. The combined qualified set contains **{g["seconds"]/60:.2f} minutes / {g["samples"]:,} samples**. Mean absolute steering-wheel-angle error is **{g["mean_abs_angle_error_deg"]:.3f}°**, RMS **{g["rms_angle_error_deg"]:.3f}°**, and the 95th percentile absolute error **{g["p95_abs_angle_error_deg"]:.3f}°**. PID demand is at or above 95% of normalized range for **{g["near_limit_percent"]:.2f}%** of qualified time; the separate logged PID saturation flag is set for **{g["pid_saturated_percent"]:.3f}%**.','', '| Route | Qualified min | Mean abs error ° | P95 abs error ° | PID demand ≥95% |','|---|---:|---:|---:|---:|']
for r in rows:
 q=r['qualified'];report.append(f'| `{r["route"]}` | {q["seconds"]/60:.2f} | {q["mean_abs_angle_error_deg"]:.3f} | {q["p95_abs_angle_error_deg"]:.3f} | {q["near_limit_percent"]:.2f}% |')
report+=['','| Speed mph | Qualified min | Mean abs error ° | P95 abs error ° | PID demand ≥95% |','|---|---:|---:|---:|---:|']
for q in j['speed_bins']:
 if q['seconds']:report.append(f'| {q["mph"]} | {q["seconds"]/60:.2f} | {q["mean_abs_angle_error_deg"]:.3f} | {q["p95_abs_angle_error_deg"]:.3f} | {q["near_limit_percent"]:.2f}% |')
report+=['', 'The lowest bin actually starts at 10 m/s (22.37 mph). There is no qualified data at 55 mph or above. Larger low-speed errors coincide with greater command demand, but these unmatched road conditions do not isolate a torque-gain cause.','', '## Output and faults','', '| Route | Controller-reported output ≥95% | Request/output difference >0.05 | Temporary fault time while ≥10 m/s |','|---|---:|---:|---:|']
for r in rows:
 o=r['controller_output'];report.append(f'| `{r["route"]}` | {o["near_limit_percent"]:.2f}% | {o["request_difference_gt_005_percent"]:.2f}% | {r["temporary_fault_moving_seconds"]:.2f} s |')
report+=['', 'Output means `carOutput.actuatorsOutput.torque`, the car controller’s reported command after its limits, not a torque sensor reading or confirmation that EPS applied it. Request/output differences also include asynchronous message timing; they are not a direct count of safety rejection. Fault time is computed over all moving samples, independently of the qualified filter. Temporary indications need investigation before interpreting large errors as a tuning problem. No permanent steering fault flag was seen in those moving samples. Full fault intervals are in `temporary_fault_intervals.json`.','', '## Method and limits','', '- Parse full rlogs; use monotonic timestamps. Align carState and carControl causally to controlsState with a maximum 100 ms age.','- Require valid messages, valid CAN, lateral PID and carControl active, speed ≥10 m/s, no steeringPressed indication, no temporary/permanent steering fault, and ≥2 seconds since lateral activation.','- Time weights use observed PID intervals up to 50 ms; larger gaps are excluded. Angle errors come from the logged PID state and agree with desired minus measured steering angle to floating-point precision. Percentiles are sample-based; averages and proportions are time-weighted.','- “No steeringPressed” is the software threshold, not proof that the driver applied no force. Road bank, tires, surface, speed and steering demand remain confounders.','- One parked route (`00000003--2fdddce87d`) has a truncated final Cap’n Proto message despite a source-matching hash. Its readable prefix is retained; it contributes no qualified samples. The three assisted routes parse without errors.','- Some startup wall-clock dates incorrectly say July 28; route IDs and monotonic elapsed times are used instead.','- The configured 0.10 s actuator delay is not a measured delay. Closed-loop tracking correlation would combine planner filtering, controller dynamics and mechanical response, so no replacement actuator-delay value is inferred here.','', '## Calibration conclusion','', 'This baseline provides measured tracking and demand metrics for a later matched comparison. It does **not** justify a new R2 torque mapping, PID gains, physical 2.5× torque claim, or a firmware safety conclusion. All available routes identify as stock; no R2-identified comparison is available. Preserve this dataset and compare any subsequent dataset with the same filtering, speed and demand ranges, accounting for the temporary EPS indications and learned steering-ratio differences.','', 'See `metrics.json`, `route_metrics.csv`, `inventory.json`, `download_integrity.json`, and `stock_baseline.png`. Per-route NPZ files preserve extracted signals; scripts are in the workspace `work` folder.']
(P/'REPORT.md').write_text('\n'.join(report)+'\n')
print('report written; fault intervals',len(faults))
