from pathlib import Path
import json,numpy as np,os
os.environ['MPLCONFIGDIR']='/tmp/tor-matplotlib'
import matplotlib;matplotlib.use('Agg')
import matplotlib.pyplot as plt
P=Path('outputs/drive_analysis_20261003');j=json.loads((P/'torque_metrics.json').read_text());active=[r for r in j['routes'] if r['qualified']['seconds']];extra=[]
fig,axs=plt.subplots(len(active),2,figsize=(12,3.5*len(active)))
for ax,r in zip(axs,active):
 a=np.load(P/(r['route']+'.npz'));z=a['est'];q=np.load(P/(r['route']+'.qualified.npz'));t=(q['t']-q['t'][0])/60;m=q['mask'];tor=q['torque'];err=tor[:,7]-tor[:,6]
 ax[0].plot(t[::30],np.where(m,err,np.nan)[::30],lw=.5);ax[0].set_title(r['route']);ax[0].set_ylabel('Lateral acceleration error (m/s²)')
 te=(z[:,0]-q['t'][0])/60;ax[1].plot(te,z[:,6],label='Factor');ax[1].plot(te,z[:,8],label='Friction');ax[1].plot(te,z[:,7],label='Offset');ax[1].legend();ax[1].set_title('Filtered estimator parameters')
 for aa in ax:aa.set_xlabel('Minutes from first controller sample');aa.grid(alpha=.2)
 v=np.where((z[:,1]>0)&(z[:,2]>0))[0];e=a['eps_status'];c=a['cs'];ix=np.clip(np.searchsorted(c[:,0],e[:,0],side='right')-1,0,len(c)-1);cs=c[ix];sel=(e[:,1]==2)&(cs[:,2]>=10)&(e[:,0]>=cs[:,0])&(e[:,0]-cs[:,0]<.1)
 extra.append({'route':r['route'],'first_valid_estimate_min':float(te[v[0]]) if len(v) else None,'moving_status2_frames':int(sel.sum()),'driver_pressed_fraction':float(np.mean(cs[sel,4]>0)) if sel.any() else None})
fig.tight_layout();fig.savefig(P/'torque_tracking.png',dpi=150);(P/'additional_checks.json').write_text(json.dumps(extra,indent=2))
lines=['# Analysis of all 15 routes downloaded October 3','', 'All 290 full rlogs (3,011,933,837 bytes) match their source SHA-256 hashes, decompress successfully and parse without errors. Each route has contiguous segment numbers starting at zero. The collection includes the three newly added routes 11, 12 and 13. Eligible tracking coverage now totals 159.09 minutes.','', '## Main findings','', 'Routes 05, 10, 11 and 12 contain active lateral control. All 15 routes use torqueState messages and report the same stock EPS identity `39990-THR-A020`. The previous angle-PID kpV/kiV comparison does not directly apply. A firmware version string does not prove the installed firmware bytes or R2 status.','', 'The estimator reaches a valid 100% calibration during route 05 and retains valid cached calibration through subsequent sessions. Routes 06–0f have no active lateral control, and their estimator point count remains 9,174: filtered values continue changing on existing data, which is not independent new calibration evidence. Route 10 adds data and finishes at 10,835 bucket points. Calibration 100% is the estimator’s coverage/validity indication, not proof of physical torque accuracy or parameter convergence.','', '## Active-drive tracking','', '| Route | Eligible minutes | Mean absolute error (m/s²) | P95 absolute error (m/s²) | Command ≥95% | Saturation flag |','|---|---:|---:|---:|---:|---:|']
for r in active:
 s=r['qualified'];lines.append(f"| {r['route']} | {s['seconds']/60:.2f} | {s['mae']:.4f} | {s['p95']:.4f} | {s['near_limit_pct']:.3f}% | {s['saturated_pct']:.3f}% |")
lines+=['','Route 10 has higher tracking errors than route 05, but these are different drives and road/speed distributions. This is not a controlled tuning comparison. Across eligible samples, command magnitude reaches 95% for 41.28 seconds; no inference about physical torque in N·m follows from normalized output.','', '## Every route','', '| Route | Segments | Active minutes | Eligible minutes | Final factor | Final offset | Final friction |','|---|---:|---:|---:|---:|---:|---:|']
manifest=json.loads((P/'collection_manifest.json').read_text())
for r in j['routes']:
 z=r['estimator']['last'];lines.append(f"| {r['route']} | {manifest['routes'][r['route']]['count']} | {r['active_seconds']/60:.2f} | {r['qualified']['seconds']/60:.2f} | {z['factor']:.4f} | {z['offset']:.4f} | {z['friction']:.4f} |")
lines+=['','Startup values are factor 1.877481, offset 0, friction 0.209698, mapping `[0,4096] → [0,4096]`, and configured delay 0.1 s. End-of-route learned values are runtime estimator outputs, not recommended fixed tuning values. All routes report branch `sp-honda-dev-202608`, commit `c04f890f684445f57c8a7cbd3f2e7f77def80397`. carParamsSP includes an Odyssey neural-network model descriptor; this alone does not prove that its feedforward option was enabled.','', '## Status and limitations','', f"Moving temporary steering-fault flags total {sum(r['temporary_moving_seconds'] for r in j['routes']):.2f} seconds; moving permanent-fault flags total {sum(r['permanent_moving_seconds'] for r in j['routes']):.2f} seconds. Raw EPS status counts are preserved in torque_metrics.json. These status flags are not a diagnostic trouble-code scan.", '', 'Tracking uses logged desiredLateralAccel minus actualLateralAccel, not the generic controller error field: extensions may transform that field into another control domain. The logged actual acceleration is a model-derived estimate, not an independent physical torque measurement. Eligibility requires fresh valid control/carState messages, active assistance for at least two seconds, valid CAN, speed ≥10 m/s, no driver steering override, and no temporary/permanent steering fault. Sample intervals above 50 ms are excluded. Means and percentages are time-weighted; percentiles are sample-weighted. Excluded interventions and faults are reported separately, not treated as successful tracking.', '', 'Earlier PID reports use steering-angle error in degrees. These torque-controller acceleration errors must not be numerically compared to those angle errors as evidence of improvement. Route dates with stale July wall clocks are left unidentified; route 05 is the October 1 long drive and route 10 is the October 3 long drive.', '', 'The logs now support evaluation of estimator adaptation and steering tracking, but not validation of a 2.5× physical torque modification. No firmware or controller settings were changed. Further tuning decisions should account for matched speed/curvature conditions and the continuing variation in learned parameters.', '', '![Tracking and calibration](torque_tracking.png)','', 'Detailed per-speed-bin metrics, estimator ranges, EPS status counts and route durations: torque_metrics.json. Parsing metadata: each route’s .parse.json. Integrity: collection_manifest.json.']
(P/'REPORT.md').write_text('\n'.join(lines)+'\n');print(extra)
print('statuses', {r['route']:r['eps_status_counts'] for r in j['routes']})
